dist: bionic
sudo: required
language: c

matrix:
  include:
    - name: Linux native compilation
      os: linux
      addons:
        hostname: lgb
        apt:
          packages:
            - alien
            - build-essential
            - bzip2
            - coreutils
            - curl
            - dpkg
            - fakeroot
            - gawk
            - gcc
            - file
            - libc-bin
            - libc6-dev
            - libcurl4-openssl-dev
            - libgtk-3-dev
            - libreadline6-dev
            - libsdl2-dev
            - make
            - rpm
            - sed
            - tar
            - vim-common
            - wget
            - zip
      compiler: gcc
      before_script:
        - set +e
        - uname -a ; lsb_release -a || true ; hostname ; pwd ; df -h ; id -a
        - hostname
        - set -e
        - sdl2-config --version --prefix --cflags --libs --static-libs
        - pkg-config --cflags-only-I --libs gtk+-3.0
        - set +e
        - ps auxwwww || true
        - uptime
      script:
        - set -e
        - make -j 2 RELEASE=yes
        - set +e
        - for a in build/bin/*.native ; do strip $a ; ls -l $a ; done
        - set -e
        - make RELEASE=yes deb
        - set +e
        - cp build/bin/*.deb build/bin/*.rpm . || true
        - build/bin/xmega65.native --help || true
        - ldd build/bin/xmega65.native
        - uptime ; pwd ; ls -l
      before_deploy:
        - build/deploy/before-deploy.sh xemu-deploy Linux
      deploy:
        provider: pages
        local_dir: xemu-deploy
        skip_cleanup: true
        github_token: $GHDEPLOYKEY2
        keep_history: false
        repo: lgblgblgb/xemu-binaries
        target_branch: binary-linux-$TRAVIS_BRANCH
        email: lgblgblgb@gmail.com
        name: Gábor Lénárt aka. LGB
        verbose: false
        on:
          branch:
            - master
            - dev
            - vic
    - name: Windows cross-compilation on Linux
      os: linux
      addons:
        hostname: lgb
        apt:
          packages:
            - binutils-mingw-w64-i686
            - binutils-mingw-w64-x86-64
            - bzip2
            - coreutils
            - file
            - gawk
            - gcc-mingw-w64-i686
            - gcc-mingw-w64-x86-64
            - make
            - nsis
            - sed
            - tar
            - vim-common
            - wget
            - zip
      before_script:
        - set +e
        - uname -a ; pwd ; df -h ; id -a
        - set -e
        - hostname
        - build/install-cross-win-mingw-sdl-on-linux.sh /usr/bin
        - set +e
        - ps auxwwww || true
        - uptime
      script:
        - set -e
        - make -j 2 ARCH=win64 RELEASE=yes
        - set +e
        - for a in build/bin/*.win64 ; do x86_64-w64-mingw32-strip $a ; ls -l $a ; done
        - cp README.md LICENSE `x86_64-w64-mingw32-sdl2-config --prefix`/bin/*.dll build/bin/
        - build/zipper.sh build/bin xemu-binaries-win64.zip build/bin/*.dll build/bin/*.win64 README.md LICENSE
        - cp build/bin/xemu-binaries-win64.zip .
        - build/nsi-build-native.sh win64 `build/system-config win64 sdl2 dll` || true
        - cp build/bin/install-xemu-win64.exe . || true
        - set -e
        - make -j 2 ARCH=win32 RELEASE=yes
        - set +e
        - for a in build/bin/*.win32 ; do i686-w64-mingw32-strip $a ; ls -l $a ; done
        - cp README.md LICENSE `i686-w64-mingw32-sdl2-config --prefix`/bin/*.dll build/bin/
        - build/zipper.sh build/bin xemu-binaries-win32.zip build/bin/*.dll build/bin/*.win32 README.md LICENSE
        - cp build/bin/xemu-binaries-win32.zip .
        - build/nsi-build-native.sh win32 `build/system-config win32 sdl2 dll` || true
        - cp build/bin/install-xemu-win32.exe . || true
        - uptime ; pwd ; ls -l
      before_deploy:
        - build/deploy/before-deploy.sh xemu-deploy Windows
      deploy:
        provider: pages
        local_dir: xemu-deploy
        skip_cleanup: true
        github_token: $GHDEPLOYKEY2
        keep_history: false
        repo: lgblgblgb/xemu-binaries
        target_branch: binary-windows-$TRAVIS_BRANCH
        email: lgblgblgb@gmail.com
        name: Gábor Lénárt aka. LGB
        verbose: false
        on:
          branch:
            - master
            - dev
            - vic
    - name: MacOS native compilation
      os: osx
      osx_image: xcode11
      addons:
        hostname: lgb
        homebrew:
          packages:
            - create-dmg
            - sdl2
      before_script:
        - set +e
        - uname -a ; pwd ; df -h ; id -a
        - hostname
        - set -e
        - sdl2-config --version --prefix --cflags --libs --static-libs
        - set +e
        - ps auxwwww || true
        - uptime
      script:
        - set -e
        - make -j 2 RELEASE=yes
        - set +e
        - for a in build/bin/*.native ; do build/mangle_dylib_osx.sh $a ; strip $a ; done
        - build/bin/xmega65.native --help || true
        - cp README.md LICENSE build/bin/
        - build/zipper.sh build/bin xemu-binaries-osx.zip build/bin/*.dylib build/bin/*.native README.md LICENSE
        - cp build/bin/xemu-binaries-osx.zip .
        - uptime ; pwd ; ls -l
      before_deploy:
        - build/dmg-osx-creator.sh
        - build/deploy/before-deploy.sh xemu-deploy MacOS
      deploy:
        provider: pages
        local_dir: xemu-deploy
        skip_cleanup: true
        github_token: $GHDEPLOYKEY2
        keep_history: false
        repo: lgblgblgb/xemu-binaries
        target_branch: binary-osx-$TRAVIS_BRANCH
        email: lgblgblgb@gmail.com
        name: Gábor Lénárt aka. LGB
        verbose: false
        on:
          branch:
            - master
            - dev
            - vic

env:
  global:
    secure: "OMFY2V+IyO53dbjtoIkPD+FBffcPI/+EhQkzqqItgqiQshKTZoeK5g8hGx6Vrj+IMKhACOD0juL7uo0yJm6B38HI0t0o8bAuKEdDsHygFRdgKe+vlf6h3FgNl5iUcFm7el352BWtXzB4CRNtoDL32xVBicBnv4LBdcks3qy7YaAN5Rq03QijlemwZxmbXAIGLCdc14fwKPGNtdrpcxNCi2dhL3zVrU2elfvozoUodrnPPmVOHLEyPXkMqlgvGz/NWrFAoq+PzEblmFtnpWFEqi2JdrTb6WYIwo+49cObArh2Musv7+eAzflqylf3yaCx0mTGIETVS+Gc2hoHN1iCMbQI3OMGWw1083Z4cBovCP58+8/wtU0Lu57Ea8QKMKViZPiAd4r0ydcei8GSdful7YYL0eux1nsF+ldB7fv0U8Bc7gWLOPHphtjFqLM7kbomaDDRH97rSYlKDehdKew+olz6xRitHuhWTkzjX92tLX18z0FV/dUc+lGjbf6R1EHg5gbhHtY7ImNktoTSc3KMr3tePESlvNeQzM5Q6zbOI5JIXUve0UqdvFTf9Bq1S73Dfmj0Ckc9kcsbPuIrSTtnoSy5T7P5HsqoUJk+ahtD3mQs/PceYsTvziBedFhUG2RPAPdOq+bg1X9QSoCxcXQthh8ZWzOcTJTwpqFhtTERWoI="
